import { execFile } from "node:child_process";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { promisify } from "node:util";

import { afterEach, describe, expect, it } from "vitest";

const execFileAsync = promisify(execFile);
const updateVersionScriptPath = resolve("scripts/update-version.mjs");
const temporaryDirectories: string[] = [];

async function createReleaseFixture() {
  const directory = await mkdtemp(join(tmpdir(), "skein-update-version-test-"));
  temporaryDirectories.push(directory);
  await mkdir(join(directory, "desktop-backend"), { recursive: true });

  await writeFile(
    join(directory, "package.json"),
    `${JSON.stringify({ name: "skein", version: "0.1.25" }, null, 2)}\n`,
  );
  await writeFile(
    join(directory, "desktop-backend", "Cargo.toml"),
    '[package]\nname = "skein"\nversion = "0.1.25"\n',
  );
  await writeFile(
    join(directory, "desktop-backend", "Cargo.lock"),
    [
      "# This file is automatically @generated by Cargo.",
      "",
      "[[package]]",
      'name = "other"',
      'version = "0.1.25"',
      "",
      "[[package]]",
      'name = "skein"',
      'version = "0.1.25"',
      "dependencies = []",
      "",
    ].join("\n"),
  );

  return directory;
}

afterEach(async () => {
  await Promise.all(
    temporaryDirectories.splice(0).map((directory) =>
      rm(directory, { recursive: true, force: true }),
    ),
  );
});

describe("update-version", () => {
  it("keeps package, Cargo manifest, and Cargo lock versions aligned", async () => {
    const directory = await createReleaseFixture();

    await execFileAsync(process.execPath, [updateVersionScriptPath, "0.1.26"], {
      cwd: directory,
    });

    const packageJson = JSON.parse(await readFile(join(directory, "package.json"), "utf8"));
    const cargoToml = await readFile(join(directory, "desktop-backend", "Cargo.toml"), "utf8");
    const cargoLock = await readFile(join(directory, "desktop-backend", "Cargo.lock"), "utf8");

    expect(packageJson.version).toBe("0.1.26");
    expect(cargoToml).toContain('version = "0.1.26"');
    expect(cargoLock).toContain('name = "other"\nversion = "0.1.25"');
    expect(cargoLock).toContain('name = "skein"\nversion = "0.1.26"');
  });
});
